/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget_2;
    QWidget *tab_3;
    QWidget *tab_4;
    QWidget *tab_5;
    QWidget *tab_6;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QGroupBox *groupBox;
    QLineEdit *idf;
    QLineEdit *nomf;
    QLineEdit *prenomf;
    QLineEdit *adressef;
    QLineEdit *emailf;
    QLineEdit *telephonef;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QPushButton *ajouter_f;
    QPushButton *pushButton_2;
    QPushButton *pushButton_5;
    QPushButton *pushButton;
    QPushButton *musique;
    QWidget *page_2;
    QGroupBox *groupBox_2;
    QLabel *label_7;
    QLineEdit *id_sp;
    QPushButton *supprimer_f;
    QPushButton *exitBtn;
    QPushButton *sendBtn;
    QWidget *layoutWidget;
    QFormLayout *formLayout;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *server;
    QLineEdit *port;
    QLineEdit *uname;
    QLineEdit *paswd;
    QLineEdit *rcpt;
    QLineEdit *subject;
    QPlainTextEdit *msg;
    QTableView *tabfourn;
    QPushButton *trier;
    QLineEdit *recherche;
    QPushButton *pushButton_3;
    QTextEdit *impc;
    QPushButton *Impdos_2;
    QWidget *tab_7;
    QPushButton *pushButton_4;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1138, 640);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        tabWidget_2 = new QTabWidget(centralwidget);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(10, 20, 1121, 531));
        tabWidget_2->setStyleSheet(QLatin1String("/*QTabWidget{\n"
"\n"
"	background-color: rgb(255, 0, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"\n"
"}\n"
"\n"
"background-color: rgb(255, 0, 0);*/\n"
"\n"
"/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"\n"
"\n"
"MIT License\n"
"\n"
"\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"\n"
"in the Software without restriction, including without limitation the rights\n"
"\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"\n"
"copies or substantial portions of the Software.\n"
"\n"
"\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"\n"
"IMPLIED, INCLUDING "
                        "BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
"\n"
"SOFTWARE.\n"
"\n"
"*/\n"
"\n"
"\n"
"\n"
"/*-----QWidget-----*/\n"
"\n"
"QWidget\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(102, 115, 140, 255),stop:1 rgba(56, 63, 77, 255));\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"\n"
"QLabel\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLabel::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	colo"
                        "r: #898988;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"\n"
"/*QMenuBar\n"
"\n"
"{\n"
"\n"
"	background-color: #484c58;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenuBar::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #898988;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenuBar::item\n"
"\n"
"{\n"
"\n"
"    background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"\n"
"{\n"
"\n"
"    background-color: #c4c5c3;\n"
"\n"
"	color: #000000;\n"
"\n"
"    border: 1px solid #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"\n"
"{\n"
"\n"
"    background-color: #979796;\n"
"\n"
"    border: 1px solid #000;\n"
"\n"
"    margin-bottom: -1px;\n"
"\n"
"    padding-bottom: 1px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"*/\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*----"
                        "-QMenu-----*/\n"
"\n"
"QMenu\n"
"\n"
"{\n"
"\n"
"    background-color: #c4c5c3;\n"
"\n"
"    border: 1px solid;\n"
"\n"
"    color: #000000;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenu::separator\n"
"\n"
"{\n"
"\n"
"    height: 1px;\n"
"\n"
"    background-color: #363942;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    padding-left: 4px;\n"
"\n"
"    margin-left: 10px;\n"
"\n"
"    margin-right: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenu::item\n"
"\n"
"{\n"
"\n"
"    min-width : 150px;\n"
"\n"
"    padding: 3px 20px 3px 20px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenu::item:selected\n"
"\n"
"{\n"
"\n"
"    background-color: #363942;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"\n"
"{\n"
"\n"
"    color: #898988;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"\n"
"QToolTip\n"
"\n"
"{\n"
"\n"
"	background-color: #bbbcba;\n"
"\n"
"	color: #000000;\n"
"\n"
"	border-color:"
                        " #051a39;\n"
"\n"
"	border : 1px solid #000000;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"\n"
"QPushButton\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 0, 0, 255),stop:1 rgba(122, 0, 0, 255));\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 1px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::hover\n"
"\n"
"{\n"
"\n"
"	background-color: #9c0000;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 1px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
""
                        "\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton::pressed\n"
"\n"
"{\n"
"\n"
"	background-color: #880000;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 2px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #000000;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"\n"
"QToolButton \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(177, 181, 193, 255),stop:1 rgba(159, 163, 174, 255));\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 1px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QToolButton::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QToolButton::hover\n"
"\n"
"{\n"
"\n"
"	background-color: "
                        "#9fa3ae;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 1px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QToolButton::pressed\n"
"\n"
"{\n"
"\n"
"	background-color: #7b7e86;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-style: solid;\n"
"\n"
"	border-width: 2px;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"	border-color: #000000;\n"
"\n"
"	padding: 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"\n"
"QComboBox\n"
"\n"
"{\n"
"\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"\n"
"    border: 1px solid #333333;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding-left: 6px;\n"
"\n"
"    color: lightgray;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"    height: 20px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox::disabled\n"
"\n"
"{\n"
"\n"
"	background-colo"
                        "r: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox:hover\n"
"\n"
"{\n"
"\n"
"    background-color: #646464;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox:on\n"
"\n"
"{\n"
"\n"
"    background-color: #979796;\n"
"\n"
"	color: #000000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"\n"
"{\n"
"\n"
"    background-color: #c4c5c3;\n"
"\n"
"    color: #000000;\n"
"\n"
"    border: 1px solid black;\n"
"\n"
"    selection-background-color: #363942;\n"
"\n"
"    selection-color: #ffffff;\n"
"\n"
"    outline: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"\n"
"{\n"
"\n"
"    subcontrol-origin: padding;\n"
"\n"
"    subcontrol-position: top right;\n"
"\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"\n"
"    border-left-color: darkgray;\n"
"\n"
"    border-left-style: solid; \n"
"\n"
"    border-top-right-radius: 3px; \n"
"\n"
"    border-bottom-rig"
                        "ht-radius: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-down.png);\n"
"\n"
"    width: 8px;\n"
"\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"\n"
"QSpinBox, \n"
"\n"
"QDoubleSpinBox,\n"
"\n"
"QDateTimeEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #000000;\n"
"\n"
"	color: #00ff00;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: 1px solid #333333;\n"
"\n"
"	padding : 4px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"\n"
"QDoubleSpinBox::disabled,\n"
"\n"
"QDateTimeEdit::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox:hover, \n"
"\n"
"QDoubleSpinBox::hover,\n"
"\n"
"QDateTimeEdit::hover\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #00ff00;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::up-button, QSpin"
                        "Box::down-button,\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"\n"
"    border: 0px solid #333333;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"\n"
"QDoubleSpinBox::disabled,\n"
"\n"
"QDateTimeEdit::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
"\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
"\n"
"{\n"
"\n"
"	background-color: #646464;\n"
"\n"
"    border: 1px solid #333333;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::up-button:disabled, QS"
                        "pinBox::down-button:disabled,\n"
"\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
"\n"
"QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
"\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
"\n"
"QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
"\n"
"{\n"
"\n"
"    background-color: #979796;\n"
"\n"
"    border: 1px solid #444444;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"\n"
"QDoubleSpinBox::down-arrow,\n"
"\n"
"QDateTimeEdit::down-arrow\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-down.png);\n"
"\n"
"    width: 7px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"\n"
"QDoubleSpinBox::up-arrow,\n"
"\n"
"QDateTimeEdit::up-arrow\n"
""
                        "\n"
"{\n"
"\n"
"    image: url(://arrow-up.png);\n"
"\n"
"    width: 7px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"\n"
"QLineEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #000000;\n"
"\n"
"	color: #00ff00;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"    border: 1px solid #333333;\n"
"\n"
"	padding: 4px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit:hover\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #00ff00;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-width: 1px;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	padding: 2px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTextEdit-----*/\n"
"\n"
"QTextEdit\n"
"\n"
"{\n"
"\n"
"	background-color: #808080;\n"
"\n"
"	color: #fff;\n"
"\n"
"	border: 1px groove #333333;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTextEdit::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565"
                        ";\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"\n"
"QGroupBox \n"
"\n"
"{\n"
"\n"
"    border: 1px groove #333333;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"    margin-top: 20px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QGroupBox \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 169, 169, 255),stop:1 rgba(122, 122, 122, 255));\n"
"\n"
"	font-weight: bold;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QGroupBox::title  \n"
"\n"
"{\n"
"\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(71, 75, 87, 255),stop:1 rgba(35, 37, 43, 255));\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 2px groove #333333;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    subcontrol-position: top left;\n"
"\n"
"    padding: 2px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QGroupBox::title::disabled\n"
"\n"
"{\n"
"\n"
"	background-"
                        "color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    subcontrol-position: top left;\n"
"\n"
"    padding: 5px;\n"
"\n"
"	border-top-left-radius: 3px;\n"
"\n"
"	border-top-right-radius: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"\n"
"QCheckBox{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"\n"
"{\n"
"\n"
"    color: #b1b1b1;\n"
"\n"
"    background-color: #323232;\n"
"\n"
"    border: 2px solid #222222;\n"
"\n"
"    width: 12px;\n"
"\n"
"    height: 12px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"\n"
"{\n"
"\n"
"    image:url(://checkbox.png);\n"
"\n"
"    border: 2px solid #00ff00;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"\n"
"{\n"
"\n"
"    border: 2px solid #00ff00;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCh"
                        "eckBox::disabled\n"
"\n"
"{\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"    border: 1px solid #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"\n"
"QRadioButton{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	color: #fff;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked\n"
"\n"
"{ \n"
"\n"
"	border: 2px inset #222222; \n"
"\n"
"	border-radius: 6px; \n"
"\n"
"	background-color:  #323232;\n"
"\n"
"	width: 9px; \n"
"\n"
"	height: 9px; \n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"\n"
"{ \n"
"\n"
"	border: 2px solid #00ff00; \n"
"\n"
"	border-radius: 5px; \n"
"\n"
"	background-color:  #323232;\n"
"\n"
"	width: 9px; \n"
"\n"
"	height: 9px; \n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator::c"
                        "hecked\n"
"\n"
"{ \n"
"\n"
"	border: 2px inset #222222; \n"
"\n"
"	border-radius: 5px; \n"
"\n"
"	background-color: #00ff00; \n"
"\n"
"	width: 9px; \n"
"\n"
"	height: 9px; \n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"\n"
"{\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"    border: 2px solid #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"\n"
"QTableView\n"
"\n"
"{\n"
"\n"
"    background-color: #808080;\n"
"\n"
"    border: 1px groove #333333;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"    gridline-color: #333333;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #242526;\n"
"\n"
"    border: 1px solid #32414B;\n"
"\n"
"    color: #656565;\n"
"\n"
"    gridline-color: #"
                        "656565;\n"
"\n"
"    outline : 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:hover \n"
"\n"
"{\n"
"\n"
"    background-color: #484c58;\n"
"\n"
"    color: #f0f0f0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected \n"
"\n"
"{\n"
"\n"
"    background-color: #484c58;\n"
"\n"
"    border: 2px groove #00ff00;\n"
"\n"
"    color: #F0F0F0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"\n"
"{\n"
"\n"
"    background-color: #1a1b1c;\n"
"\n"
"    border: 2px solid #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"\n"
"{\n"
"\n"
"    background-color: #282830;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section\n"
"\n"
"{\n"
"\n"
"    background-color: #282830;\n"
"\n"
"    color: #fff;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"    text-align: left;\n"
"\n"
"	padding: 4px;\n"
"\n"
"	\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:d"
                        "isabled\n"
"\n"
"{\n"
"\n"
"    background-color: #525251;\n"
"\n"
"    color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"\n"
"{\n"
"\n"
"    background-color: #00ff00;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"\n"
"{\n"
"\n"
"    color: #656565;\n"
"\n"
"    background-color: #525251;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"\n"
"QHeaderView::section::vertical::only-one\n"
"\n"
"{\n"
"\n"
"    border-top: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"\n"
"{\n"
"\n"
"    border-top: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"\n"
"QHeaderView::section::horizontal::only-one\n"
"\n"
"{\n"
"\n"
"    border-left: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"\n"
"{\n"
"\n"
"    border-left: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
""
                        "\n"
"\n"
"\n"
"\n"
"/*-----QTabWidget-----*/\n"
"\n"
"QTabBar::tab\n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	width: 150px;\n"
"\n"
"	height: 20px;\n"
"\n"
"	\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #656565;\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabWidget::pane \n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border: 1px groove #333333;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"\n"
"{\n"
"\n"
"    background-color: #484c58;\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border: 1px groove #333333;\n"
"\n"
"	border-bottom: 0px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"\n"
"{\n"
"\n"
"    ba"
                        "ckground-color: #a3a7b2;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"\n"
"{\n"
"\n"
"    background-color: #484c58;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:top:!selected \n"
"\n"
"{\n"
"\n"
"    margin-top: 1px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"\n"
"{\n"
"\n"
"    margin-bottom: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"\n"
"{\n"
"\n"
"    min-width: 8ex;\n"
"\n"
"    margin-right: -1px;\n"
"\n"
"    padding: 5px 10px 5px 10px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:top:selected \n"
"\n"
"{\n"
"\n"
"    border-bottom-color: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"\n"
"{\n"
"\n"
"    border-top-color: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
""
                        "\n"
"{\n"
"\n"
"    margin-right: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:left:!selected \n"
"\n"
"{\n"
"\n"
"    margin-right: 2px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:right:!selected\n"
"\n"
"{\n"
"\n"
"    margin-left: 2px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"\n"
"{\n"
"\n"
"    min-height: 15ex;\n"
"\n"
"    margin-bottom: -1px;\n"
"\n"
"    padding: 10px 5px 10px 5px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:left:selected \n"
"\n"
"{\n"
"\n"
"    border-left-color: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:right:selected \n"
"\n"
"{\n"
"\n"
"    border-right-color: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"\n"
"{\n"
"\n"
"    margin-bottom: 0;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
""
                        "\n"
"QSlider{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal \n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	height: 6px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"\n"
"	border: 1px solid #000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	border: 1px solid #000; \n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"\n"
"	border: 1px solid #000; \n"
"\n"
"	width: 12px;\n"
"\n"
"	margin-top: -6px;\n"
"\n"
"	margin-bottom: -6px;\n"
"\n"
"\n"
""
                        "\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"\n"
"{\n"
"\n"
"	background-color: #808080;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #bbb;\n"
"\n"
"	border-color: #999;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #eee;\n"
"\n"
"	border-color: #999;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #eee;\n"
"\n"
"	border: 1px solid #aaa;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:vertical \n"
"\n"
"{\n"
"\n"
"	background-color: transparent;\n"
"\n"
"	width: 6px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::sub-page:vertical \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"\n"
"	"
                        "border: 1px solid #000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::add-page:vertical \n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	border: 1px solid #000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:vertical \n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"\n"
"	border: 1px solid #000;\n"
"\n"
"	height: 12px;\n"
"\n"
"	margin-left: -6px;\n"
"\n"
"	margin-right: -6px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:vertical:hover \n"
"\n"
"{\n"
"\n"
"	background-color: #808080;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::sub-page:vertical:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #bbb;\n"
"\n"
"	border-color: #999;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::add-page:vertical:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #eee;\n"
"\n"
"	border-color: #999;\n"
"\n"
"\n"
"\n"
""
                        "}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:vertical:disabled \n"
"\n"
"{\n"
"\n"
"	background-color: #eee;\n"
"\n"
"	border: 1px solid #aaa;\n"
"\n"
"	border-radius: 3px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QDial-----*/\n"
"\n"
"QDial\n"
"\n"
"{\n"
"\n"
"	background-color: #600000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QDial::disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"\n"
"QScrollBar:horizontal\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #222222;\n"
"\n"
"    background-color: #63676d;\n"
"\n"
"    height: 18px;\n"
"\n"
"    margin: 0px 18px 0 18px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"\n"
"{\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"	border: 1px solid #656565;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"    min-height: 20px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"\n"
"{\n"
"\n"
"    border"
                        ": 1px solid #1b1b19;\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"    width: 18px;\n"
"\n"
"    subcontrol-position: right;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #1b1b19;\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"    width: 18px;\n"
"\n"
"    subcontrol-position: left;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-right.png);\n"
"\n"
"    width: 8px;\n"
"\n"
"    height: 8px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-left.png);\n"
"\n"
"    width: 8px;\n"
"\n"
"    height: 8px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"\n"
"{\n"
"\n"
"    background: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
""
                        "\n"
"\n"
"QScrollBar:vertical\n"
"\n"
"{\n"
"\n"
"    background-color: #63676d;\n"
"\n"
"    width: 18px;\n"
"\n"
"    margin: 18px 0 18px 0;\n"
"\n"
"    border: 1px solid #222222;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"\n"
"{\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"	border: 1px solid #656565;\n"
"\n"
"	border-radius: 2px;\n"
"\n"
"    min-height: 20px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #1b1b19;\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"    height: 18px;\n"
"\n"
"    subcontrol-position: bottom;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"\n"
"{\n"
"\n"
"    border: 1px solid #1b1b19;\n"
"\n"
"    background-color: #a6acb3;\n"
"\n"
"    height: 18px;\n"
"\n"
"    subcontrol-position: top;\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollB"
                        "ar::up-arrow:vertical\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-up.png);\n"
"\n"
"    width: 8px;\n"
"\n"
"    height: 8px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"\n"
"{\n"
"\n"
"    image: url(://arrow-down.png);\n"
"\n"
"    width: 8px;\n"
"\n"
"    height: 8px;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"\n"
"{\n"
"\n"
"    background: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"\n"
"QProgressBar\n"
"\n"
"{\n"
"\n"
"	background-color: #000;\n"
"\n"
"	color: #00ff00;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"	border: 0px groove #000;\n"
"\n"
"	border-radius: 10px;\n"
"\n"
"	text-align: center;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QProgressBar:disabled\n"
"\n"
"{\n"
"\n"
"	background-color: #404040;\n"
"\n"
"	color: #656565;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	border: 1px solid #000;\n"
"\n"
"	border-radius: 10px;\n"
"\n"
"	text-alig"
                        "n: center;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QProgressBar::chunk {\n"
"\n"
"	background-color: #ffaf02;\n"
"\n"
"	border: 0px;\n"
"\n"
"	border-radius: 10px;\n"
"\n"
"	color: #000;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"\n"
"	background-color: #333;\n"
"\n"
"	border: 0px;\n"
"\n"
"	border-radius: 10px;\n"
"\n"
"	color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"\n"
"QStatusBar\n"
"\n"
"{\n"
"\n"
"	background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(102, 115, 140, 255),stop:1 rgba(56, 63, 77, 255));\n"
"\n"
"	color: #ffffff;\n"
"\n"
"	border-color: #051a39;\n"
"\n"
"	font-weight: bold;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
""));
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tabWidget_2->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        tabWidget_2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        tabWidget_2->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        stackedWidget = new QStackedWidget(tab_6);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(10, 10, 501, 481));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        groupBox = new QGroupBox(page);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 30, 481, 291));
        idf = new QLineEdit(groupBox);
        idf->setObjectName(QStringLiteral("idf"));
        idf->setGeometry(QRect(100, 50, 113, 22));
        nomf = new QLineEdit(groupBox);
        nomf->setObjectName(QStringLiteral("nomf"));
        nomf->setGeometry(QRect(90, 120, 113, 22));
        prenomf = new QLineEdit(groupBox);
        prenomf->setObjectName(QStringLiteral("prenomf"));
        prenomf->setGeometry(QRect(90, 180, 113, 22));
        adressef = new QLineEdit(groupBox);
        adressef->setObjectName(QStringLiteral("adressef"));
        adressef->setGeometry(QRect(90, 240, 291, 22));
        emailf = new QLineEdit(groupBox);
        emailf->setObjectName(QStringLiteral("emailf"));
        emailf->setGeometry(QRect(280, 50, 191, 22));
        telephonef = new QLineEdit(groupBox);
        telephonef->setObjectName(QStringLiteral("telephonef"));
        telephonef->setGeometry(QRect(280, 120, 191, 22));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(5, 50, 91, 20));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 120, 61, 20));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 180, 56, 16));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 240, 56, 16));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(240, 50, 56, 16));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(220, 120, 71, 20));
        ajouter_f = new QPushButton(page);
        ajouter_f->setObjectName(QStringLiteral("ajouter_f"));
        ajouter_f->setGeometry(QRect(30, 380, 93, 28));
        pushButton_2 = new QPushButton(page);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(310, 380, 93, 28));
        pushButton_5 = new QPushButton(page);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(170, 380, 93, 28));
        pushButton = new QPushButton(page);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(480, 0, 20, 20));
        musique = new QPushButton(page);
        musique->setObjectName(QStringLiteral("musique"));
        musique->setGeometry(QRect(20, 0, 31, 31));
        musique->setStyleSheet(QStringLiteral("font: 75 14pt \"MS Shell Dlg 2\";"));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        groupBox_2 = new QGroupBox(page_2);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(-10, 0, 561, 511));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 40, 91, 20));
        id_sp = new QLineEdit(groupBox_2);
        id_sp->setObjectName(QStringLiteral("id_sp"));
        id_sp->setGeometry(QRect(120, 40, 113, 22));
        supprimer_f = new QPushButton(groupBox_2);
        supprimer_f->setObjectName(QStringLiteral("supprimer_f"));
        supprimer_f->setGeometry(QRect(280, 40, 93, 28));
        exitBtn = new QPushButton(groupBox_2);
        exitBtn->setObjectName(QStringLiteral("exitBtn"));
        exitBtn->setGeometry(QRect(400, 300, 93, 28));
        sendBtn = new QPushButton(groupBox_2);
        sendBtn->setObjectName(QStringLiteral("sendBtn"));
        sendBtn->setGeometry(QRect(401, 370, 93, 28));
        layoutWidget = new QWidget(groupBox_2);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(20, 80, 339, 380));
        formLayout = new QFormLayout(layoutWidget);
        formLayout->setObjectName(QStringLiteral("formLayout"));
        formLayout->setFieldGrowthPolicy(QFormLayout::ExpandingFieldsGrow);
        formLayout->setRowWrapPolicy(QFormLayout::WrapLongRows);
        formLayout->setVerticalSpacing(9);
        formLayout->setContentsMargins(0, 0, 0, 0);
        label_8 = new QLabel(layoutWidget);
        label_8->setObjectName(QStringLiteral("label_8"));

        formLayout->setWidget(0, QFormLayout::LabelRole, label_8);

        label_9 = new QLabel(layoutWidget);
        label_9->setObjectName(QStringLiteral("label_9"));

        formLayout->setWidget(1, QFormLayout::LabelRole, label_9);

        label_10 = new QLabel(layoutWidget);
        label_10->setObjectName(QStringLiteral("label_10"));

        formLayout->setWidget(2, QFormLayout::LabelRole, label_10);

        label_11 = new QLabel(layoutWidget);
        label_11->setObjectName(QStringLiteral("label_11"));

        formLayout->setWidget(3, QFormLayout::LabelRole, label_11);

        label_12 = new QLabel(layoutWidget);
        label_12->setObjectName(QStringLiteral("label_12"));

        formLayout->setWidget(4, QFormLayout::LabelRole, label_12);

        label_13 = new QLabel(layoutWidget);
        label_13->setObjectName(QStringLiteral("label_13"));

        formLayout->setWidget(5, QFormLayout::LabelRole, label_13);

        label_14 = new QLabel(layoutWidget);
        label_14->setObjectName(QStringLiteral("label_14"));

        formLayout->setWidget(6, QFormLayout::LabelRole, label_14);

        server = new QLineEdit(layoutWidget);
        server->setObjectName(QStringLiteral("server"));

        formLayout->setWidget(0, QFormLayout::FieldRole, server);

        port = new QLineEdit(layoutWidget);
        port->setObjectName(QStringLiteral("port"));

        formLayout->setWidget(1, QFormLayout::FieldRole, port);

        uname = new QLineEdit(layoutWidget);
        uname->setObjectName(QStringLiteral("uname"));

        formLayout->setWidget(2, QFormLayout::FieldRole, uname);

        paswd = new QLineEdit(layoutWidget);
        paswd->setObjectName(QStringLiteral("paswd"));
        paswd->setEchoMode(QLineEdit::Password);

        formLayout->setWidget(3, QFormLayout::FieldRole, paswd);

        rcpt = new QLineEdit(layoutWidget);
        rcpt->setObjectName(QStringLiteral("rcpt"));

        formLayout->setWidget(4, QFormLayout::FieldRole, rcpt);

        subject = new QLineEdit(layoutWidget);
        subject->setObjectName(QStringLiteral("subject"));

        formLayout->setWidget(5, QFormLayout::FieldRole, subject);

        msg = new QPlainTextEdit(layoutWidget);
        msg->setObjectName(QStringLiteral("msg"));

        formLayout->setWidget(6, QFormLayout::FieldRole, msg);

        stackedWidget->addWidget(page_2);
        tabfourn = new QTableView(tab_6);
        tabfourn->setObjectName(QStringLiteral("tabfourn"));
        tabfourn->setGeometry(QRect(510, 30, 511, 281));
        trier = new QPushButton(tab_6);
        trier->setObjectName(QStringLiteral("trier"));
        trier->setGeometry(QRect(1020, 40, 93, 28));
        recherche = new QLineEdit(tab_6);
        recherche->setObjectName(QStringLiteral("recherche"));
        recherche->setGeometry(QRect(532, 0, 301, 22));
        pushButton_3 = new QPushButton(tab_6);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(1020, 190, 93, 28));
        impc = new QTextEdit(tab_6);
        impc->setObjectName(QStringLiteral("impc"));
        impc->setGeometry(QRect(510, 330, 511, 161));
        Impdos_2 = new QPushButton(tab_6);
        Impdos_2->setObjectName(QStringLiteral("Impdos_2"));
        Impdos_2->setGeometry(QRect(1020, 350, 93, 28));
        tabWidget_2->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        tabWidget_2->addTab(tab_7, QString());
        pushButton_4 = new QPushButton(centralwidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(440, 560, 93, 28));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1138, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget_2->setCurrentIndex(3);
        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QApplication::translate("MainWindow", "G.employee", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QApplication::translate("MainWindow", "G.client", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("MainWindow", "G.services", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "Ajout fournisseur", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "ID fournisseur", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Nom ", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Prenom ", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "E-mail", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "Telephone", Q_NULLPTR));
        ajouter_f->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "Annuler", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        pushButton->setText(QString());
        musique->setText(QApplication::translate("MainWindow", " \360\235\204\236", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Supprimer les informations d'un fournisseur", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "ID fournisseur", Q_NULLPTR));
        supprimer_f->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        exitBtn->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        sendBtn->setText(QApplication::translate("MainWindow", "Send", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Smtp-server:", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Server port:", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Username:", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Password:", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Recipant to:", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Subject:", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Message:", Q_NULLPTR));
        server->setText(QApplication::translate("MainWindow", "smtp.gmail.com", Q_NULLPTR));
        port->setText(QApplication::translate("MainWindow", "465", Q_NULLPTR));
        uname->setText(QApplication::translate("MainWindow", "mohamedabdelatif.aouadh@esprit.tn", Q_NULLPTR));
        paswd->setInputMask(QString());
        paswd->setText(QApplication::translate("MainWindow", "201JMT3405", Q_NULLPTR));
        subject->setText(QApplication::translate("MainWindow", "Projet By M.Aouadh", Q_NULLPTR));
        trier->setText(QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("MainWindow", "excel", Q_NULLPTR));
        Impdos_2->setText(QApplication::translate("MainWindow", "imprimer-pdf", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QApplication::translate("MainWindow", "G.fournisseurs", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QApplication::translate("MainWindow", "G.produits", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "localisation", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
