/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QStackedWidget *stackedWidget;
    QWidget *page_ajouter;
    QLabel *label;
    QLabel *label_nom;
    QLabel *label_adresse;
    QLabel *label_prenom;
    QLabel *label_tel;
    QLabel *label_fonc;
    QLabel *label_salaire;
    QLabel *label_ev;
    QLineEdit *lineEdit_nom;
    QLineEdit *lineEdit_prenom;
    QLineEdit *lineEdit_adresse;
    QLineEdit *lineEdit_tel;
    QLineEdit *lineEdit_salaire;
    QRadioButton *radio1_ev;
    QRadioButton *radio2_ev;
    QRadioButton *radio3_ev;
    QPushButton *bouton_valider;
    QPushButton *bouton_annuler;
    QComboBox *comboBox_ajouter;
    QPushButton *bouton_page2;
    QWidget *page_modifier;
    QLabel *label_2;
    QLabel *label_nom_2;
    QLabel *label_prenom_2;
    QLabel *label_tel_2;
    QLabel *label_adresse_2;
    QLabel *label_salaire_2;
    QLabel *label_fonc_2;
    QLabel *label_ev_2;
    QLineEdit *lineEdit_nom_2;
    QLineEdit *lineEdit_prenom_2;
    QLineEdit *lineEdit_adresse_2;
    QLineEdit *lineEdit_tel_2;
    QLineEdit *lineEdit_salaire_2;
    QRadioButton *radio1_ev_2;
    QRadioButton *radio2_ev_2;
    QRadioButton *radio3_ev_2;
    QPushButton *bouton_modifier;
    QPushButton *bouton_annuler_mdf;
    QComboBox *comboBox_modifier;
    QLabel *label_3;
    QLabel *label_nom_3;
    QPushButton *bouton_supprimer;
    QPushButton *bouton_page1;
    QLabel *label_nom_4;
    QLineEdit *lineEdit_mat_modif;
    QPushButton *bouton_mat_modifier;
    QComboBox *comboBox_supression;
    QPushButton *boutonpg_2_vers_3;
    QWidget *page_fonct_avance;
    QLabel *label_4;
    QTableView *tab_employes_tri;
    QLabel *label_5;
    QRadioButton *radio_tri1;
    QRadioButton *radio_tri2;
    QRadioButton *radio_tri3;
    QLabel *label_6;
    QRadioButton *radio_rech2;
    QRadioButton *radio_rech3;
    QRadioButton *radio_rech1;
    QPushButton *boutonpg_3_vers_2;
    QLineEdit *lineEdit_recherche;
    QTableView *tab_recherche;
    QPushButton *boutonpg_3_vers_4;
    QWidget *page_gestion_profils;
    QPushButton *boutonpg_4_vers_3;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_12;
    QLabel *label_11;
    QLabel *label_nom_5;
    QComboBox *comboBox_matricule_profils;
    QPushButton *bouton_ok_matricule_profil;
    QLineEdit *lineEdit_login;
    QLineEdit *lineEdit_mp_profil;
    QLabel *label_nom_6;
    QLabel *label_nom_7;
    QPushButton *bouton_ajouter_profil;
    QLabel *label_13;
    QLabel *label_nom_8;
    QLabel *label_nom_9;
    QLineEdit *lineEdit_login_modifier;
    QPushButton *bouton_ok_login_modifier;
    QLineEdit *lineEdit_mp_modifier;
    QPushButton *bouton_modifier_profil;
    QLabel *label_14;
    QComboBox *comboBox_supression_profils;
    QPushButton *bouton_supprimer_profil;
    QTableView *tab_employes;
    QLabel *label_7;
    QLabel *label_employe_connecte;
    QPushButton *boutonConnexion;
    QTextEdit *listeMessages;
    QPushButton *boutonEnvoyer;
    QLineEdit *message;
    QLineEdit *pseudo;
    QLabel *label_fonc_3;
    QPushButton *bouton_deconnecter;
    QLabel *label_15;
    QLabel *label_nom_10;
    QComboBox *comboBox_mat_bulletin_depaie;
    QPushButton *bouton_generer_bp;
    QWidget *tab_2;
    QWidget *tab_3;
    QWidget *tab_4;
    QWidget *tab_5;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(900, 727);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 900, 721));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        stackedWidget = new QStackedWidget(tab);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(20, 40, 381, 501));
        stackedWidget->setFrameShape(QFrame::StyledPanel);
        page_ajouter = new QWidget();
        page_ajouter->setObjectName(QStringLiteral("page_ajouter"));
        label = new QLabel(page_ajouter);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 0, 171, 41));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label->setMargin(0);
        label_nom = new QLabel(page_ajouter);
        label_nom->setObjectName(QStringLiteral("label_nom"));
        label_nom->setGeometry(QRect(20, 65, 56, 16));
        label_nom->setFont(font);
        label_adresse = new QLabel(page_ajouter);
        label_adresse->setObjectName(QStringLiteral("label_adresse"));
        label_adresse->setGeometry(QRect(20, 135, 71, 16));
        label_adresse->setFont(font);
        label_prenom = new QLabel(page_ajouter);
        label_prenom->setObjectName(QStringLiteral("label_prenom"));
        label_prenom->setGeometry(QRect(20, 100, 71, 16));
        label_prenom->setFont(font);
        label_tel = new QLabel(page_ajouter);
        label_tel->setObjectName(QStringLiteral("label_tel"));
        label_tel->setGeometry(QRect(20, 170, 101, 16));
        label_tel->setFont(font);
        label_fonc = new QLabel(page_ajouter);
        label_fonc->setObjectName(QStringLiteral("label_fonc"));
        label_fonc->setGeometry(QRect(20, 240, 81, 16));
        label_fonc->setFont(font);
        label_salaire = new QLabel(page_ajouter);
        label_salaire->setObjectName(QStringLiteral("label_salaire"));
        label_salaire->setGeometry(QRect(20, 205, 81, 16));
        label_salaire->setFont(font);
        label_ev = new QLabel(page_ajouter);
        label_ev->setObjectName(QStringLiteral("label_ev"));
        label_ev->setGeometry(QRect(20, 275, 201, 16));
        label_ev->setFont(font);
        lineEdit_nom = new QLineEdit(page_ajouter);
        lineEdit_nom->setObjectName(QStringLiteral("lineEdit_nom"));
        lineEdit_nom->setGeometry(QRect(115, 60, 230, 22));
        lineEdit_prenom = new QLineEdit(page_ajouter);
        lineEdit_prenom->setObjectName(QStringLiteral("lineEdit_prenom"));
        lineEdit_prenom->setGeometry(QRect(115, 95, 230, 22));
        lineEdit_adresse = new QLineEdit(page_ajouter);
        lineEdit_adresse->setObjectName(QStringLiteral("lineEdit_adresse"));
        lineEdit_adresse->setGeometry(QRect(115, 130, 230, 22));
        lineEdit_tel = new QLineEdit(page_ajouter);
        lineEdit_tel->setObjectName(QStringLiteral("lineEdit_tel"));
        lineEdit_tel->setGeometry(QRect(115, 165, 230, 22));
        lineEdit_salaire = new QLineEdit(page_ajouter);
        lineEdit_salaire->setObjectName(QStringLiteral("lineEdit_salaire"));
        lineEdit_salaire->setGeometry(QRect(115, 200, 230, 22));
        radio1_ev = new QRadioButton(page_ajouter);
        radio1_ev->setObjectName(QStringLiteral("radio1_ev"));
        radio1_ev->setGeometry(QRect(210, 300, 121, 20));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        radio1_ev->setFont(font1);
        radio2_ev = new QRadioButton(page_ajouter);
        radio2_ev->setObjectName(QStringLiteral("radio2_ev"));
        radio2_ev->setGeometry(QRect(210, 330, 97, 20));
        radio2_ev->setFont(font1);
        radio3_ev = new QRadioButton(page_ajouter);
        radio3_ev->setObjectName(QStringLiteral("radio3_ev"));
        radio3_ev->setGeometry(QRect(210, 360, 97, 20));
        radio3_ev->setFont(font1);
        bouton_valider = new QPushButton(page_ajouter);
        bouton_valider->setObjectName(QStringLiteral("bouton_valider"));
        bouton_valider->setGeometry(QRect(30, 400, 93, 28));
        bouton_valider->setFont(font1);
        bouton_annuler = new QPushButton(page_ajouter);
        bouton_annuler->setObjectName(QStringLiteral("bouton_annuler"));
        bouton_annuler->setGeometry(QRect(145, 400, 93, 28));
        bouton_annuler->setFont(font1);
        comboBox_ajouter = new QComboBox(page_ajouter);
        comboBox_ajouter->setObjectName(QStringLiteral("comboBox_ajouter"));
        comboBox_ajouter->setGeometry(QRect(115, 235, 230, 22));
        bouton_page2 = new QPushButton(page_ajouter);
        bouton_page2->setObjectName(QStringLiteral("bouton_page2"));
        bouton_page2->setGeometry(QRect(300, 470, 75, 25));
        bouton_page2->setFont(font1);
        stackedWidget->addWidget(page_ajouter);
        page_modifier = new QWidget();
        page_modifier->setObjectName(QStringLiteral("page_modifier"));
        label_2 = new QLabel(page_modifier);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, -10, 341, 41));
        label_2->setFont(font);
        label_2->setMargin(0);
        label_nom_2 = new QLabel(page_modifier);
        label_nom_2->setObjectName(QStringLiteral("label_nom_2"));
        label_nom_2->setGeometry(QRect(20, 65, 56, 16));
        label_nom_2->setFont(font);
        label_prenom_2 = new QLabel(page_modifier);
        label_prenom_2->setObjectName(QStringLiteral("label_prenom_2"));
        label_prenom_2->setGeometry(QRect(20, 100, 71, 16));
        label_prenom_2->setFont(font);
        label_tel_2 = new QLabel(page_modifier);
        label_tel_2->setObjectName(QStringLiteral("label_tel_2"));
        label_tel_2->setGeometry(QRect(20, 170, 101, 16));
        label_tel_2->setFont(font);
        label_adresse_2 = new QLabel(page_modifier);
        label_adresse_2->setObjectName(QStringLiteral("label_adresse_2"));
        label_adresse_2->setGeometry(QRect(20, 135, 71, 16));
        label_adresse_2->setFont(font);
        label_salaire_2 = new QLabel(page_modifier);
        label_salaire_2->setObjectName(QStringLiteral("label_salaire_2"));
        label_salaire_2->setGeometry(QRect(20, 205, 81, 16));
        label_salaire_2->setFont(font);
        label_fonc_2 = new QLabel(page_modifier);
        label_fonc_2->setObjectName(QStringLiteral("label_fonc_2"));
        label_fonc_2->setGeometry(QRect(20, 240, 81, 16));
        label_fonc_2->setFont(font);
        label_ev_2 = new QLabel(page_modifier);
        label_ev_2->setObjectName(QStringLiteral("label_ev_2"));
        label_ev_2->setGeometry(QRect(20, 275, 201, 16));
        label_ev_2->setFont(font);
        lineEdit_nom_2 = new QLineEdit(page_modifier);
        lineEdit_nom_2->setObjectName(QStringLiteral("lineEdit_nom_2"));
        lineEdit_nom_2->setGeometry(QRect(115, 60, 230, 22));
        lineEdit_prenom_2 = new QLineEdit(page_modifier);
        lineEdit_prenom_2->setObjectName(QStringLiteral("lineEdit_prenom_2"));
        lineEdit_prenom_2->setGeometry(QRect(115, 95, 230, 22));
        lineEdit_adresse_2 = new QLineEdit(page_modifier);
        lineEdit_adresse_2->setObjectName(QStringLiteral("lineEdit_adresse_2"));
        lineEdit_adresse_2->setGeometry(QRect(115, 130, 230, 22));
        lineEdit_tel_2 = new QLineEdit(page_modifier);
        lineEdit_tel_2->setObjectName(QStringLiteral("lineEdit_tel_2"));
        lineEdit_tel_2->setGeometry(QRect(115, 165, 230, 22));
        lineEdit_salaire_2 = new QLineEdit(page_modifier);
        lineEdit_salaire_2->setObjectName(QStringLiteral("lineEdit_salaire_2"));
        lineEdit_salaire_2->setGeometry(QRect(115, 200, 230, 22));
        radio1_ev_2 = new QRadioButton(page_modifier);
        radio1_ev_2->setObjectName(QStringLiteral("radio1_ev_2"));
        radio1_ev_2->setGeometry(QRect(230, 275, 121, 20));
        radio1_ev_2->setFont(font1);
        radio2_ev_2 = new QRadioButton(page_modifier);
        radio2_ev_2->setObjectName(QStringLiteral("radio2_ev_2"));
        radio2_ev_2->setGeometry(QRect(230, 305, 97, 20));
        radio2_ev_2->setFont(font1);
        radio3_ev_2 = new QRadioButton(page_modifier);
        radio3_ev_2->setObjectName(QStringLiteral("radio3_ev_2"));
        radio3_ev_2->setGeometry(QRect(230, 340, 97, 20));
        radio3_ev_2->setFont(font1);
        bouton_modifier = new QPushButton(page_modifier);
        bouton_modifier->setObjectName(QStringLiteral("bouton_modifier"));
        bouton_modifier->setGeometry(QRect(70, 370, 93, 28));
        bouton_modifier->setFont(font1);
        bouton_annuler_mdf = new QPushButton(page_modifier);
        bouton_annuler_mdf->setObjectName(QStringLiteral("bouton_annuler_mdf"));
        bouton_annuler_mdf->setGeometry(QRect(200, 370, 93, 28));
        bouton_annuler_mdf->setFont(font1);
        comboBox_modifier = new QComboBox(page_modifier);
        comboBox_modifier->setObjectName(QStringLiteral("comboBox_modifier"));
        comboBox_modifier->setGeometry(QRect(115, 235, 200, 22));
        label_3 = new QLabel(page_modifier);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 395, 191, 41));
        label_3->setFont(font);
        label_3->setMargin(0);
        label_nom_3 = new QLabel(page_modifier);
        label_nom_3->setObjectName(QStringLiteral("label_nom_3"));
        label_nom_3->setGeometry(QRect(20, 435, 91, 21));
        label_nom_3->setFont(font);
        bouton_supprimer = new QPushButton(page_modifier);
        bouton_supprimer->setObjectName(QStringLiteral("bouton_supprimer"));
        bouton_supprimer->setGeometry(QRect(230, 435, 93, 26));
        bouton_supprimer->setFont(font1);
        bouton_page1 = new QPushButton(page_modifier);
        bouton_page1->setObjectName(QStringLiteral("bouton_page1"));
        bouton_page1->setGeometry(QRect(220, 470, 75, 25));
        bouton_page1->setFont(font1);
        label_nom_4 = new QLabel(page_modifier);
        label_nom_4->setObjectName(QStringLiteral("label_nom_4"));
        label_nom_4->setGeometry(QRect(20, 30, 91, 16));
        label_nom_4->setFont(font);
        lineEdit_mat_modif = new QLineEdit(page_modifier);
        lineEdit_mat_modif->setObjectName(QStringLiteral("lineEdit_mat_modif"));
        lineEdit_mat_modif->setGeometry(QRect(115, 30, 100, 22));
        bouton_mat_modifier = new QPushButton(page_modifier);
        bouton_mat_modifier->setObjectName(QStringLiteral("bouton_mat_modifier"));
        bouton_mat_modifier->setGeometry(QRect(230, 30, 93, 22));
        bouton_mat_modifier->setFont(font1);
        comboBox_supression = new QComboBox(page_modifier);
        comboBox_supression->setObjectName(QStringLiteral("comboBox_supression"));
        comboBox_supression->setGeometry(QRect(115, 435, 100, 25));
        boutonpg_2_vers_3 = new QPushButton(page_modifier);
        boutonpg_2_vers_3->setObjectName(QStringLiteral("boutonpg_2_vers_3"));
        boutonpg_2_vers_3->setGeometry(QRect(300, 470, 75, 25));
        boutonpg_2_vers_3->setFont(font1);
        stackedWidget->addWidget(page_modifier);
        page_fonct_avance = new QWidget();
        page_fonct_avance->setObjectName(QStringLiteral("page_fonct_avance"));
        label_4 = new QLabel(page_fonct_avance);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, -5, 341, 41));
        label_4->setFont(font);
        label_4->setMargin(0);
        tab_employes_tri = new QTableView(page_fonct_avance);
        tab_employes_tri->setObjectName(QStringLiteral("tab_employes_tri"));
        tab_employes_tri->setGeometry(QRect(10, 70, 351, 191));
        label_5 = new QLabel(page_fonct_avance);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 25, 111, 41));
        label_5->setFont(font);
        label_5->setMargin(0);
        radio_tri1 = new QRadioButton(page_fonct_avance);
        radio_tri1->setObjectName(QStringLiteral("radio_tri1"));
        radio_tri1->setGeometry(QRect(110, 40, 97, 20));
        radio_tri1->setFont(font1);
        radio_tri2 = new QRadioButton(page_fonct_avance);
        radio_tri2->setObjectName(QStringLiteral("radio_tri2"));
        radio_tri2->setGeometry(QRect(180, 40, 97, 20));
        radio_tri2->setFont(font1);
        radio_tri3 = new QRadioButton(page_fonct_avance);
        radio_tri3->setObjectName(QStringLiteral("radio_tri3"));
        radio_tri3->setGeometry(QRect(270, 40, 97, 20));
        radio_tri3->setFont(font1);
        label_6 = new QLabel(page_fonct_avance);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 260, 221, 41));
        label_6->setFont(font);
        label_6->setMargin(0);
        radio_rech2 = new QRadioButton(page_fonct_avance);
        radio_rech2->setObjectName(QStringLiteral("radio_rech2"));
        radio_rech2->setGeometry(QRect(120, 295, 141, 20));
        radio_rech2->setFont(font1);
        radio_rech3 = new QRadioButton(page_fonct_avance);
        radio_rech3->setObjectName(QStringLiteral("radio_rech3"));
        radio_rech3->setGeometry(QRect(270, 295, 97, 20));
        radio_rech3->setFont(font1);
        radio_rech1 = new QRadioButton(page_fonct_avance);
        radio_rech1->setObjectName(QStringLiteral("radio_rech1"));
        radio_rech1->setGeometry(QRect(20, 295, 97, 20));
        radio_rech1->setFont(font1);
        boutonpg_3_vers_2 = new QPushButton(page_fonct_avance);
        boutonpg_3_vers_2->setObjectName(QStringLiteral("boutonpg_3_vers_2"));
        boutonpg_3_vers_2->setGeometry(QRect(220, 470, 75, 25));
        boutonpg_3_vers_2->setFont(font1);
        lineEdit_recherche = new QLineEdit(page_fonct_avance);
        lineEdit_recherche->setObjectName(QStringLiteral("lineEdit_recherche"));
        lineEdit_recherche->setGeometry(QRect(20, 325, 331, 22));
        tab_recherche = new QTableView(page_fonct_avance);
        tab_recherche->setObjectName(QStringLiteral("tab_recherche"));
        tab_recherche->setGeometry(QRect(10, 355, 351, 110));
        boutonpg_3_vers_4 = new QPushButton(page_fonct_avance);
        boutonpg_3_vers_4->setObjectName(QStringLiteral("boutonpg_3_vers_4"));
        boutonpg_3_vers_4->setGeometry(QRect(300, 470, 75, 25));
        boutonpg_3_vers_4->setFont(font1);
        stackedWidget->addWidget(page_fonct_avance);
        page_gestion_profils = new QWidget();
        page_gestion_profils->setObjectName(QStringLiteral("page_gestion_profils"));
        boutonpg_4_vers_3 = new QPushButton(page_gestion_profils);
        boutonpg_4_vers_3->setObjectName(QStringLiteral("boutonpg_4_vers_3"));
        boutonpg_4_vers_3->setGeometry(QRect(220, 470, 75, 25));
        boutonpg_4_vers_3->setFont(font1);
        label_8 = new QLabel(page_gestion_profils);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, -5, 351, 41));
        label_8->setFont(font);
        label_8->setMargin(0);
        label_9 = new QLabel(page_gestion_profils);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 25, 371, 41));
        QFont font2;
        font2.setPointSize(8);
        font2.setBold(true);
        font2.setWeight(75);
        label_9->setFont(font2);
        label_9->setTextFormat(Qt::AutoText);
        label_9->setMargin(0);
        label_10 = new QLabel(page_gestion_profils);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 45, 371, 41));
        label_10->setFont(font2);
        label_10->setTextFormat(Qt::AutoText);
        label_10->setMargin(0);
        label_12 = new QLabel(page_gestion_profils);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 65, 371, 41));
        label_12->setFont(font2);
        label_12->setTextFormat(Qt::AutoText);
        label_12->setMargin(0);
        label_11 = new QLabel(page_gestion_profils);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 90, 351, 41));
        label_11->setFont(font);
        label_11->setMargin(0);
        label_nom_5 = new QLabel(page_gestion_profils);
        label_nom_5->setObjectName(QStringLiteral("label_nom_5"));
        label_nom_5->setGeometry(QRect(10, 130, 91, 21));
        label_nom_5->setFont(font);
        comboBox_matricule_profils = new QComboBox(page_gestion_profils);
        comboBox_matricule_profils->setObjectName(QStringLiteral("comboBox_matricule_profils"));
        comboBox_matricule_profils->setGeometry(QRect(125, 130, 100, 25));
        bouton_ok_matricule_profil = new QPushButton(page_gestion_profils);
        bouton_ok_matricule_profil->setObjectName(QStringLiteral("bouton_ok_matricule_profil"));
        bouton_ok_matricule_profil->setGeometry(QRect(240, 130, 41, 26));
        bouton_ok_matricule_profil->setFont(font1);
        lineEdit_login = new QLineEdit(page_gestion_profils);
        lineEdit_login->setObjectName(QStringLiteral("lineEdit_login"));
        lineEdit_login->setGeometry(QRect(125, 165, 201, 22));
        lineEdit_mp_profil = new QLineEdit(page_gestion_profils);
        lineEdit_mp_profil->setObjectName(QStringLiteral("lineEdit_mp_profil"));
        lineEdit_mp_profil->setGeometry(QRect(125, 195, 101, 22));
        lineEdit_mp_profil->setEchoMode(QLineEdit::Password);
        label_nom_6 = new QLabel(page_gestion_profils);
        label_nom_6->setObjectName(QStringLiteral("label_nom_6"));
        label_nom_6->setGeometry(QRect(10, 165, 91, 21));
        label_nom_6->setFont(font);
        label_nom_7 = new QLabel(page_gestion_profils);
        label_nom_7->setObjectName(QStringLiteral("label_nom_7"));
        label_nom_7->setGeometry(QRect(10, 195, 111, 21));
        label_nom_7->setFont(font);
        bouton_ajouter_profil = new QPushButton(page_gestion_profils);
        bouton_ajouter_profil->setObjectName(QStringLiteral("bouton_ajouter_profil"));
        bouton_ajouter_profil->setGeometry(QRect(240, 195, 93, 25));
        bouton_ajouter_profil->setFont(font1);
        label_13 = new QLabel(page_gestion_profils);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 225, 351, 41));
        label_13->setFont(font);
        label_13->setMargin(0);
        label_nom_8 = new QLabel(page_gestion_profils);
        label_nom_8->setObjectName(QStringLiteral("label_nom_8"));
        label_nom_8->setGeometry(QRect(10, 260, 91, 21));
        label_nom_8->setFont(font);
        label_nom_9 = new QLabel(page_gestion_profils);
        label_nom_9->setObjectName(QStringLiteral("label_nom_9"));
        label_nom_9->setGeometry(QRect(10, 290, 191, 21));
        label_nom_9->setFont(font);
        lineEdit_login_modifier = new QLineEdit(page_gestion_profils);
        lineEdit_login_modifier->setObjectName(QStringLiteral("lineEdit_login_modifier"));
        lineEdit_login_modifier->setGeometry(QRect(70, 260, 201, 22));
        bouton_ok_login_modifier = new QPushButton(page_gestion_profils);
        bouton_ok_login_modifier->setObjectName(QStringLiteral("bouton_ok_login_modifier"));
        bouton_ok_login_modifier->setGeometry(QRect(280, 260, 41, 26));
        bouton_ok_login_modifier->setFont(font1);
        lineEdit_mp_modifier = new QLineEdit(page_gestion_profils);
        lineEdit_mp_modifier->setObjectName(QStringLiteral("lineEdit_mp_modifier"));
        lineEdit_mp_modifier->setGeometry(QRect(200, 290, 101, 22));
        lineEdit_mp_modifier->setEchoMode(QLineEdit::Password);
        bouton_modifier_profil = new QPushButton(page_gestion_profils);
        bouton_modifier_profil->setObjectName(QStringLiteral("bouton_modifier_profil"));
        bouton_modifier_profil->setGeometry(QRect(130, 320, 93, 25));
        bouton_modifier_profil->setFont(font1);
        label_14 = new QLabel(page_gestion_profils);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 345, 351, 41));
        label_14->setFont(font);
        label_14->setMargin(0);
        comboBox_supression_profils = new QComboBox(page_gestion_profils);
        comboBox_supression_profils->setObjectName(QStringLiteral("comboBox_supression_profils"));
        comboBox_supression_profils->setGeometry(QRect(40, 390, 151, 25));
        bouton_supprimer_profil = new QPushButton(page_gestion_profils);
        bouton_supprimer_profil->setObjectName(QStringLiteral("bouton_supprimer_profil"));
        bouton_supprimer_profil->setGeometry(QRect(210, 390, 93, 25));
        bouton_supprimer_profil->setFont(font1);
        stackedWidget->addWidget(page_gestion_profils);
        tab_employes = new QTableView(tab);
        tab_employes->setObjectName(QStringLiteral("tab_employes"));
        tab_employes->setGeometry(QRect(420, 35, 461, 301));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(430, 0, 351, 41));
        label_7->setFont(font);
        label_7->setMargin(0);
        label_employe_connecte = new QLabel(tab);
        label_employe_connecte->setObjectName(QStringLiteral("label_employe_connecte"));
        label_employe_connecte->setGeometry(QRect(20, 0, 281, 41));
        label_employe_connecte->setFont(font);
        label_employe_connecte->setMargin(0);
        boutonConnexion = new QPushButton(tab);
        boutonConnexion->setObjectName(QStringLiteral("boutonConnexion"));
        boutonConnexion->setGeometry(QRect(460, 350, 341, 31));
        boutonConnexion->setFont(font1);
        listeMessages = new QTextEdit(tab);
        listeMessages->setObjectName(QStringLiteral("listeMessages"));
        listeMessages->setGeometry(QRect(420, 390, 461, 201));
        listeMessages->setReadOnly(true);
        boutonEnvoyer = new QPushButton(tab);
        boutonEnvoyer->setObjectName(QStringLiteral("boutonEnvoyer"));
        boutonEnvoyer->setGeometry(QRect(820, 610, 71, 41));
        boutonEnvoyer->setFont(font1);
        message = new QLineEdit(tab);
        message->setObjectName(QStringLiteral("message"));
        message->setGeometry(QRect(579, 600, 231, 51));
        pseudo = new QLineEdit(tab);
        pseudo->setObjectName(QStringLiteral("pseudo"));
        pseudo->setGeometry(QRect(430, 620, 141, 31));
        label_fonc_3 = new QLabel(tab);
        label_fonc_3->setObjectName(QStringLiteral("label_fonc_3"));
        label_fonc_3->setGeometry(QRect(430, 600, 141, 16));
        label_fonc_3->setFont(font2);
        bouton_deconnecter = new QPushButton(tab);
        bouton_deconnecter->setObjectName(QStringLiteral("bouton_deconnecter"));
        bouton_deconnecter->setGeometry(QRect(310, 10, 93, 28));
        bouton_deconnecter->setFont(font1);
        label_15 = new QLabel(tab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 540, 221, 41));
        label_15->setFont(font);
        label_15->setMargin(0);
        label_nom_10 = new QLabel(tab);
        label_nom_10->setObjectName(QStringLiteral("label_nom_10"));
        label_nom_10->setGeometry(QRect(20, 580, 91, 21));
        label_nom_10->setFont(font);
        comboBox_mat_bulletin_depaie = new QComboBox(tab);
        comboBox_mat_bulletin_depaie->setObjectName(QStringLiteral("comboBox_mat_bulletin_depaie"));
        comboBox_mat_bulletin_depaie->setGeometry(QRect(115, 580, 100, 25));
        bouton_generer_bp = new QPushButton(tab);
        bouton_generer_bp->setObjectName(QStringLiteral("bouton_generer_bp"));
        bouton_generer_bp->setGeometry(QRect(240, 580, 93, 26));
        bouton_generer_bp->setFont(font1);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 900, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);
        stackedWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Tunisian Dry Cleaner", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Ajouter un employ\303\251 :", Q_NULLPTR));
        label_nom->setText(QApplication::translate("MainWindow", "Nom :", Q_NULLPTR));
        label_adresse->setText(QApplication::translate("MainWindow", "Adresse :", Q_NULLPTR));
        label_prenom->setText(QApplication::translate("MainWindow", "Pr\303\251nom :", Q_NULLPTR));
        label_tel->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone :", Q_NULLPTR));
        label_fonc->setText(QApplication::translate("MainWindow", "Fonction :", Q_NULLPTR));
        label_salaire->setText(QApplication::translate("MainWindow", "Salaire :", Q_NULLPTR));
        label_ev->setText(QApplication::translate("MainWindow", "\303\211valuation de rendement:", Q_NULLPTR));
        radio1_ev->setText(QApplication::translate("MainWindow", "Satisfaisante", Q_NULLPTR));
        radio2_ev->setText(QApplication::translate("MainWindow", "Bonne", Q_NULLPTR));
        radio3_ev->setText(QApplication::translate("MainWindow", "Exellente", Q_NULLPTR));
        bouton_valider->setText(QApplication::translate("MainWindow", "Valider", Q_NULLPTR));
        bouton_annuler->setText(QApplication::translate("MainWindow", "Annuler", Q_NULLPTR));
        bouton_page2->setText(QApplication::translate("MainWindow", "Suivant", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Modifier un employ\303\251 :", Q_NULLPTR));
        label_nom_2->setText(QApplication::translate("MainWindow", "Nom :", Q_NULLPTR));
        label_prenom_2->setText(QApplication::translate("MainWindow", "Pr\303\251nom :", Q_NULLPTR));
        label_tel_2->setText(QApplication::translate("MainWindow", "T\303\251l\303\251phone :", Q_NULLPTR));
        label_adresse_2->setText(QApplication::translate("MainWindow", "Adresse :", Q_NULLPTR));
        label_salaire_2->setText(QApplication::translate("MainWindow", "Salaire :", Q_NULLPTR));
        label_fonc_2->setText(QApplication::translate("MainWindow", "Fonction :", Q_NULLPTR));
        label_ev_2->setText(QApplication::translate("MainWindow", "\303\211valuation de rendement:", Q_NULLPTR));
        radio1_ev_2->setText(QApplication::translate("MainWindow", "Satisfaisante", Q_NULLPTR));
        radio2_ev_2->setText(QApplication::translate("MainWindow", "Bonne", Q_NULLPTR));
        radio3_ev_2->setText(QApplication::translate("MainWindow", "Exellente", Q_NULLPTR));
        bouton_modifier->setText(QApplication::translate("MainWindow", "Ok", Q_NULLPTR));
        bouton_annuler_mdf->setText(QApplication::translate("MainWindow", "Annuler", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Supprimer un employ\303\251 :", Q_NULLPTR));
        label_nom_3->setText(QApplication::translate("MainWindow", "Matricule :", Q_NULLPTR));
        bouton_supprimer->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        bouton_page1->setText(QApplication::translate("MainWindow", "Pr\303\251c\303\251dent", Q_NULLPTR));
        label_nom_4->setText(QApplication::translate("MainWindow", "Matricule :", Q_NULLPTR));
        bouton_mat_modifier->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        boutonpg_2_vers_3->setText(QApplication::translate("MainWindow", "Suivant", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "Autres fonctionnalit\303\251s :", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "Trier par :", Q_NULLPTR));
        radio_tri1->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        radio_tri2->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        radio_tri3->setText(QApplication::translate("MainWindow", "Salaire", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "Chercher un employ\303\251 selon :", Q_NULLPTR));
        radio_rech2->setText(QApplication::translate("MainWindow", "Nom ou pr\303\251nom", Q_NULLPTR));
        radio_rech3->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        radio_rech1->setText(QApplication::translate("MainWindow", "Matricule", Q_NULLPTR));
        boutonpg_3_vers_2->setText(QApplication::translate("MainWindow", "Pr\303\251c\303\251dent", Q_NULLPTR));
        boutonpg_3_vers_4->setText(QApplication::translate("MainWindow", "Suivant", Q_NULLPTR));
        boutonpg_4_vers_3->setText(QApplication::translate("MainWindow", "Pr\303\251c\303\251dent", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Gestion des profils (L'authentification) :", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Remarque : le login du profil est toujours par d\303\251faut ", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "compos\303\251 de votre matricule plus votre nom et vous", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", " ne pouvez jamais le modifier .", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Ajouter un profil :", Q_NULLPTR));
        label_nom_5->setText(QApplication::translate("MainWindow", "Matricule :", Q_NULLPTR));
        bouton_ok_matricule_profil->setText(QApplication::translate("MainWindow", "Ok", Q_NULLPTR));
        label_nom_6->setText(QApplication::translate("MainWindow", "Login :", Q_NULLPTR));
        label_nom_7->setText(QApplication::translate("MainWindow", "Mot de passe :", Q_NULLPTR));
        bouton_ajouter_profil->setText(QApplication::translate("MainWindow", "Valider", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Modifier profil (Changer le mot de passe ) :", Q_NULLPTR));
        label_nom_8->setText(QApplication::translate("MainWindow", "Login :", Q_NULLPTR));
        label_nom_9->setText(QApplication::translate("MainWindow", "Nouveau mot de passe :", Q_NULLPTR));
        bouton_ok_login_modifier->setText(QApplication::translate("MainWindow", "Ok", Q_NULLPTR));
        bouton_modifier_profil->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Supprimer un profil :", Q_NULLPTR));
        bouton_supprimer_profil->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "La liste des employ\303\251s :", Q_NULLPTR));
        label_employe_connecte->setText(QString());
        boutonConnexion->setText(QApplication::translate("MainWindow", "D\303\251mmarer le Chat", Q_NULLPTR));
        boutonEnvoyer->setText(QApplication::translate("MainWindow", "Envoyer", Q_NULLPTR));
        label_fonc_3->setText(QApplication::translate("MainWindow", "Login :", Q_NULLPTR));
        bouton_deconnecter->setText(QApplication::translate("MainWindow", "D\303\251connecter", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "G\303\251n\303\251rer un bulletin de paie :", Q_NULLPTR));
        label_nom_10->setText(QApplication::translate("MainWindow", "Matricule :", Q_NULLPTR));
        bouton_generer_bp->setText(QApplication::translate("MainWindow", "Ok", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Gestion des employ\303\251s", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Gestion des clients", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Gestion des services", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Gestion des fournisseurs", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Gestion des produits", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
